### ISSUE TITLE
Setup directory layout

### ISSUE THREAD

**Issue by elementbound** [foxssake/dumber-dungeons#15]
### Done criteria

- Setup a monorepo structure
  - `server/` should contain the backend
  - `client/` should contain the frontend ( including both the game and the control view, i.e. display and phone )
  - `shared/` should contain shared configs
  - `game/` can be created later, it will contain the game logic and definitions
- Setup [rush] to manage the monorepo
- Proposed structure:
```
.
├── server/
│   ├── src/
│   ├── package.json
│   └── tsconfig.json
├── client/
│   ├── src/
│   ├── package.json
│   └── tsconfig.json
├── game/
│   ├── src/
│   ├── package.json
│   └── tsconfig.json
├── shared/
│   └── tsconfig.json
├── package.json
└── eslint.config.mjs
```

### Notes

For further context, see comments:
- https://github.com/foxssake/dumber-dungeons/pull/31#discussion_r1856266495
- https://github.com/foxssake/dumber-dungeons/pull/31#discussion_r1856281170

### Questions

- :heavy_check_mark:  Do we need `shared/package.json`?
  - No, unless we want to export code from there
- :heavy_check_mark:  Do we need `shared/tsconfig.js`, or should we just have a `tsconfig.json` at root?
  - Root only contain IDE configs, like `eslint.config.mjs` or `.prettierrc`

### Related issues

Depends on #14

[rush]: https://rushjs.io/

**Comment by ocsi0520** [comment]
- I guess we don't need shared/package.json. That's not a package, rather a bunch of files which are reused in multiple projects/packages.
- I would say let's have a `shared/tsconfig.json`, and each project/package can extend it, and modify it to its needs. I.e. for `server` we must not have _DOM_ in the `lib` array, but for the frontend parts we must have it.

**Comment by ocsi0520** [comment]
Since these 3 separate projects does not add up to an aggregate package, therefore we shouldn't have a `package.json` in root config.
Also IMHO we should not have any file in the "root" folder. In case we have something to share among the projects (i.e. Pub-Sub pattern), then we should put it into the "shared" folder.
In case we have a game-related code which is shared between "client" and "server", that should be placed in the "game" folder.

So:
- "shared" can't import anything outside of "shared" folder
- "game" can only import from "game" and "shared"
- "client" can import from itself + "game" + "shared"
- "server" can import from itself "game" + "shared"

**Comment by elementbound** [comment]
Updated questions as discussed.
